export class DelegatorSummary {
  constructor(
    address,
    allowance,
    bondedAmount,
    delegateAddress,
    delegatedAmount,
    fees,
    lastClaimRound,
    pendingFees,
    pendingStake,
    startRound,
    status,
    withdrawRound,
    withdrawAmount,
    nextUnbondingLockId,
    totalStake,
    delegateCalledReward,
    totalStakeInLPT,
    bondedAmountInLPT
  ) {
    this.address = address ? address : '',
    this.allowance = allowance ? allowance : '0',
    this.bondedAmount = bondedAmount ? bondedAmount : '0',
    this.delegateAddress = delegateAddress ? delegateAddress : '',
    this.delegatedAmount = delegatedAmount ? delegatedAmount : '0',
    this.fees = fees ? fees : '0',
    this.lastClaimRound = lastClaimRound ? lastClaimRound : '0',
    this.pendingFees = pendingFees ? pendingFees : '0',
    this.pendingStake = pendingStake ? pendingStake : '0',
    this.startRound = startRound ? startRound : '0',
    this.status = status ? status : '',
    this.withdrawRound = withdrawRound ? withdrawRound : '0',
    this.withdrawAmount = withdrawAmount ? withdrawAmount : '0',
    this.nextUnbondingLockId = nextUnbondingLockId ? nextUnbondingLockId : '0',
    this.totalStake = totalStake ? totalStake : '0',
    this.delegateCalledReward = delegateCalledReward ? delegateCalledReward : false,
    this.totalStakeInLPT = totalStakeInLPT ? totalStakeInLPT : '0',
    this.bondedAmountInLPT = bondedAmountInLPT ? bondedAmountInLPT : '0'
  }
}
