export const LOADING_USER_DATA = 'Loading user data'
export const WELCOME_AGAIN = 'Welcome Again! '
export const WELCOME_NEW_SUBSCRIBER = 'Welcome to Livepeer! '
export const WELCOME_NOT_SUBSCRIBED = 'Welcome to Livepeer!'
export const FAIL_NO_REASON = 'Something went wrong!, please try again later!'
export const LOADING_UNSUBSCRIPTION = 'Please wait while we process your unsubscription'
export const LOADING_SUBSCRIPTION = 'Please wait while we process your subscription'
