const DAILY_FREQUENCY = 'daily'
const WEEKLY_FREQUENCY = 'weekly'
const SUPPORTED_FREQUENCIES = [DAILY_FREQUENCY, WEEKLY_FREQUENCY]

module.exports = {
  DAILY_FREQUENCY,
  WEEKLY_FREQUENCY,
  SUPPORTED_FREQUENCIES,
}
