const DAILY_FREQUENCY = 'daily'
const WEEKLY_FREQUENCY = 'weekly'
const SUPPORTED_FREQUENCIES = [DAILY_FREQUENCY, WEEKLY_FREQUENCY]
const MAX_RETRIES = process.env.MAX_RETRIES || 5
module.exports = {
  DAILY_FREQUENCY,
  WEEKLY_FREQUENCY,
  SUPPORTED_FREQUENCIES,
  MAX_RETRIES,
}
