export const NO_WEB3 = 'Please install metamask and come back!'
export const NO_PERMISSIONS = 'You need to accept the permissions to use our app!'
export const NO_ADDRESS = 'You need to provide a valid address to use our app!'
export const WRONG_NETWORK = 'You are on the wrong network, you need to use ... in order to use our app!'
export const DEFAULT_ERROR = 'Something went wrong!'
export const WAITING_AUTHORIZATION = 'Requesting Authorization...'
