export const NO_WEB3 = 'The user does not have web3 injected'
export const NO_PERMISSIONS = 'The user did not gave us permissions'
export const WRONG_NETWORK = 'The user is not logged on the correct network'
export const NO_ADDRESS = 'The user did not provided a valid address'
export const NO_REASON = 'Something went wrong!'
